### ISSUE TITLE
module 'cgi' has no attribute 'escape'

### ISSUE THREAD

**Issue by thickas** [wolever/pip2pi#111]
### Error message:
c:\dir2pi .
Traceback (most recent call last):
  File "e:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Python38\Scripts\dir2pi.exe\__main__.py", line 7, in <module>
  File "e:\python38\lib\site-packages\libpip2pi\commands.py", line 316, in dir2pi
    return _dir2pi(option, argv)
  File "e:\python38\lib\site-packages\libpip2pi\commands.py", line 388, in _dir2pi
    cgi.escape(pkg_dir_name),
AttributeError: module 'cgi' has no attribute 'escape'

### Code in file   commands.py ,line 386

if pkg_name not in processed_pkg:
            pkg_index += "<a href='%s/'>%s</a><br />\n" % (
                cgi.escape(pkg_dir_name),
                cgi.escape(pkg_name),
            )
            processed_pkg.add(pkg_name)

        if option.build_html:
            with open(os.path.join(pkg_dir, "index.html"), "a") as fp:
                fp.write("<a href='%(name)s'>%(name)s</a><br />\n" % {
                    "name": cgi.escape(pkg_basename),
                })

**Comment by re0phimes** [comment]
same error

**Comment by Chise1** [comment]
same error

**Comment by AviVarma** [comment]
I have this too

**Comment by liaomingg** [comment]
pip2pi v0.8.2 [Latest](https://github.com/wolever/pip2pi/releases/latest)
@[safiyat](https://github.com/safiyat) safiyat released this 04 Aug 2021
[ v0.8.2](https://github.com/wolever/pip2pi/tree/v0.8.2)
https://github.com/wolever/pip2pi/commit/7dd84371221a38b9dc934e6ea386969356d4a5a7
Changed cgi.escape to html.escape.
Works with Python 3.8+ now.
